spring.application.name=smart_village
server.port=8080
server.servlet.context-path=/smart_village

spring.datasource.url=jdbc:postgresql://43.229.149.138:5432/smartvillage
spring.datasource.username=smartvillageadmin
spring.datasource.password=9aY5Ep%jRlrIf.D0U
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=CHANGE_ME_32_CHAR_SECRET_KEY_123456
# token expiry in milliseconds: 30 days = 2592000000 ms
jwt.expiration-minutes=2592000000


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-parameter-count=200

app.upload.dir=/root/uploads